currency_list = ['Afghan Afghani', 'Albanian Lek', 'Algerian Dinar', 'Angolan Kwanza',
                 'Argentine Peso', 'Armenian Dram', 'Aruban Florin', 'Australian Dollar',
                 'Azerbaijani Manat', 'Bahamian Dollar','Bahraini Dinar', 'Bajan Dollar',
                 'Bangladeshi Taka', 'Belarusian Ruble', 'Belize Dollar',
                 'Bermudan Dollar', 'Bhutan Currency', 'Bolivian Boliviano',
                 'Bosnia-Herzegovina Convertible Mark','Botswanan Pula', 'Brazilian Real',
                 'Brunei Dollar', 'Bulgarian Lev', 'Burundian Franc','CFP Franc',
                 'Cambodian Riel', 'Canadian Dollar', 'Cape Verdean Escudo',
                 'Cayman Islands Dollar','Central African CFA franc', 'Chilean Peso',
                 'Chilean Unit of Account (UF)', 'Chinese Yuan','Colombian Peso',
                 'Comorian Franc', 'Congolese Franc', 'Costa Rican Colón', 'Croatian Kuna',
                 'Cuban Peso', 'Czech Koruna', 'Danish Krone', 'Djiboutian Franc',
                 'Dominican Peso','East Caribbean Dollar','Egyptian Pound','Ethiopian Birr',
                 'Euro', 'Fijian Dollar', 'Gambian Dalasi', 'Georgian Lari', 'Ghanaian Cedi',
                 'Guatemalan Quetzal', 'Guinean Franc', 'Guyanaese Dollar', 'Haitian Gourde',
                 'Honduran Lempira','Hong Kong Dollar','Hungarian Forint','Icelandic Krona',
                 'Indian Rupee','Indonesian Rupiah', 'Iranian Rial', 'Iraqi Dinar',
                 'Israel New Shekel', 'Jamaican Dollar', 'Japanese Yen', 'Jordanian Dinar',
                 'Kazakhstani Tenge', 'Kenyan Shilling', 'Kuwaiti Dinar', 'Kyrgyzstani Som',
'Laotian Kip','Lebanese Pound','Lesotho Loti','Liberian Dollar','Libyan       Dinar','Macanese Pataca', 'Macedonian Denar', 'Malaasy Ariary', 'Malawian Kwacha', 'Malaysian Ringgit', 'Maldivian Rufiyaa', 'Mauritanian Rupee', 'Mexican   Peso','Moldovan Leu', 'Moroccon Dirham', 'Mozambican Metical','Myanmar Kyat','Namibian Dollar', 'Nepalese Rupee', 'Netherlands Antillean Guilder','New Taiwan Dollar','New Zealand Dollar','Nicaraguan Cordoba','Nigerian   Naira','Norwegian Krone', 'Omani Rial', 'Pakistani Rupee', 'Panamanian Balboa','Papua New Guinean Kina', 'Paraguayan Guarani', 'Philippine Peso','Poland Zloty','Pound Sterling','Qatari Rial','Romanian Leu','Russian Ruble','Rwandan Franc', 'Salvadoran Colon', 'Saudi Riyal', 'Serbian Dinar','Seychellois Rupee', 'Sierra Leonean Leone' , 'Singapore Dollar' , 'Sol','Solomon Islands Dollar' , 'Somali Shilling', 'South African Rand' , 'South Korean Won' , 'Sovereign Bolivar', 'Sri Lankan Rupee' , 'Sudanese Pound','Surinamese Dollar' , 'Swazi Lilangeni' , 'Swedish Krona', 'Swiss Franc','Tajikistani Somoni' , 'Tanzanian Shilling' , 'Thai Bhat', "Tongan Pa'anga" ,'Trinidad & Tobago Dollar','Tunisian Dollar','Turkish Iira','Turkmenistani Manat','Ugandan Shilling', 'Ukranian Hryvnia' , 'United Arab Emirates Dirham','United States Dollar', 'Uruguayan Peso', 'Uzbekistani Som', 'Vietnamese Dong ','West African CFA Franc ', 'Yemeni Rial' , 'Zambian Kwacha']
